### ISSUE TITLE
Multiple maps in one component or view

### ISSUE THREAD

**Issue by num-lock** [phegman/vue-mapbox-gl#10]
The hard coded ID property with the value `map` (both in the template and the code) makes it impossible to use multiple `<mapbox>` components in the same parent component or at the same time, e.g. `Sample.vue`:

```
<template>
  <div class="sample">
    <mapbox ...></mapbox>
    <mapbox ...></mapbox>
  </div>
</template>

<script>
...
</script>

<style>
...
</style>
```

The same issue arises when there are multiple maps from different components visible in the same view.

I tried to get it to work with some `this._uid`-hackery, but that made me do my own component in the end and didn't seem to work well with Mapbox anyways.

**Comment by phegman** [comment]
Hi,

Good point, I didn't think of that scenario. I just pushed an update that should allow you to do this. Now when defining the `map-options` just pass in the `container` and that will be used as the component id. If it isn't passed in it will just default to "map"

Example:
```html
<mapbox 
	access-token="your access token"
	:map-options="{
		style: 'mapbox://styles/mapbox/light-v9',
		center: [-96, 37.8],
		zoom: 3,
		container: 'map-1'
	}">
</mapbox>
<mapbox 
	access-token="your access token"
	:map-options="{
		style: 'mapbox://styles/mapbox/light-v9',
		center: [-96, 37.8],
		zoom: 3,
		container: 'map-2'
	}">
</mapbox>
```
