### ISSUE TITLE
Support for mapbox-gl-draw

### ISSUE THREAD

**Issue by amaurymartiny** [phegman/vue-mapbox-gl#12]
Would it be possible to use [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw) with this library?

An example with vanilla JavaScript can be found here: https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

**Comment by phegman** [comment]
I just pushed an update that makes this possible. This update adds the `map-init` event which gets passed the map object. So you can do something like this:

```html
<mapbox
	access-token="your access token"
	:map-options="{
    	style: 'mapbox://styles/mapbox/light-v9',
    	center: [-96, 37.8],
    	zoom: 3
    }"
	:geolocate-control="{
		show: true, 
		position: 'top-left'
	}"
	:scale-control="{
		show: true,
		position: 'top-left'
	}"
	:fullscreen-control="{
		show: true,
		position: 'top-left'
	}"
	@map-init="mapInit">
</mapbox>
```

And then in your main JS file you can do something like this...

```javascript
export default {
	data() {
		return {

		}
	},
	components: {
        'mapbox': Mapbox
    },
	methods: {
		mapInit(map) {
			const Draw = new MapboxDraw();

			map.addControl(Draw);
		}
	}
}
```
