### ISSUE TITLE
Geocoding control?

### ISSUE THREAD

**Issue by humblecoder** [phegman/vue-mapbox-gl#13]
I may be missing something, but is there an option for a geocoding control as found in the documentation here:

https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

**Comment by phegman** [comment]
Hi Michael,

Take a look at this issue...https://github.com/phegman/vue-mapbox-gl/issues/12

You should be able to implement the Geocoder the same way, by just swapping in the Geocoder instead of the Draw plugin
