### ISSUE TITLE
How to bind markers to vue components

### ISSUE THREAD

**Issue by edanweis** [phegman/vue-mapbox-gl#16]
How can I use computed properties, or store with mounted components bound to mapbox markers? 

I am mounting components to markers in a forEach loop, but I cannot change their content dynamically after mounting.

```
  const makerContent = Vue.extend(Marker)

  features.forEach(function(feature, index) {
    var parent = document.createElement('div')
        parent.classList.add("mapboxgl-marker")
    var child = document.createElement('div')
        child.classList.add("marker")
    parent.appendChild(child)
     const marker = new mapboxgl.Marker(parent)
     .setLngLat(feature.geometry.coordinates)
     .addTo(self.map)

    new makerContent({
      store: store,
      propsData: {
        feature: feature, 
      }
    }).$mount(child); 
  })
```

Any suggestions?

**Comment by phegman** [comment]
Hi Edan,

It looks like you are using Vuex in this example? Where is the `Marker` element you are extending coming from? I would try something like this (keep in mind I have not tested this)

```javascript
const markerContent = Vue.extend({
  template: '<div class="marker-content"></div>',
  computed: {
    someVuexData() {
      return this.$store.getters.someVuexData;
    }
  }
});

features.forEach(function(feature, index) {
  var parent = document.createElement('div');
  parent.classList.add("mapboxgl-marker");

  const marker = new mapboxgl.Marker(parent)
    .setLngLat(feature.geometry.coordinates)
    .addTo(self.map);

  // Bind marker content to marker wrapper
  new markerContent().$mount(parent);
});
```

**Comment by edanweis** [comment]
Thanks @phegman, `Marker` is a component as you have written, with a Vuex store. But if I store the entire `features` object, changes to `features` would not reflected in the `Marker` component, because the data is not binding, until the `forEach()` loop is run again.

I thought there must be a simpler way with dynamic `propsData` or if vue could bind to a ES6 map state. That would avoid duplicating the `Feature` in Vuex and the `forEach()` loop.

Any Ideas?

**Comment by phegman** [comment]
Hi Edan,

Okay I think I am following, you could try passing the feature into the data object of the Marker component, although I am not sure if you would be able to use a separate .vue file with this approach. Anyways something like this may work (again, I have not tested):

```javascript
features.forEach(function(feature, index) {
  var parent = document.createElement('div');
  parent.classList.add("mapboxgl-marker");

  const markerContent = Vue.extend({
    template: '<div class="marker-content"></div>',
    data() {
      return {
        feature: feature
      }
    }
  });

  const marker = new mapboxgl.Marker(parent)
    .setLngLat(feature.geometry.coordinates)
    .addTo(self.map);

  // Bind marker content to marker wrapper
  new markerContent().$mount(parent);
});
```

**Comment by edanweis** [comment]
Yes, using both `propsData` and `data` passes data, but it is not binding. Changes to my `feature` value doesn't update the data or props in the component. I think because it is defined only once upon creation during the `forEach()` loop. If the data was binding, then every marker could update with changes to their geoJSON format.

**Comment by phegman** [comment]
I believe this is expected behavior with Vue and a good use case for Vuex as each Marker component has its own data. You will need to use Vuex for the shared features or update the data via Events and an Event Bus. I would personally just use Vuex though.

**Comment by Jones-S** [comment]
Was there a working solution to bind data to a marker?
It seems that your results were never binding the data, am I correct?
I am currently still trying to get your version to work...
