### ISSUE TITLE
how to create simple points/Markers? 

### ISSUE THREAD

**Issue by FabianSilva** [phegman/vue-mapbox-gl#17]
new mapboxgl.Marker(el)
  .setLngLat(marker.geometry.coordinates)
  .addTo(map);

some examples tell about L.marker but L is not available.
how I can add points on vue-mapbox-gl?

https://www.mapbox.com/help/custom-markers-gl-js/

**Comment by phegman** [comment]
L.marker is for [Leaflet](http://leafletjs.com/) so it won't be available in this package. You can add a new marker to the map by using the `map-load` event.
