### ISSUE TITLE
warning using vue-mapbox-gl on Quasar Framework

### ISSUE THREAD

**Issue by FabianSilva** [phegman/vue-mapbox-gl#18]
I'm imported vue-mapbox-gl and when see debug console a message appears, I can ommit it or have to do something? the map is visible and seems to work well.

thanks.

***Message:***

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Mapbox>
       <Lista> at src\components\Lista.vue
         <QLayout>
           <App> at src\App.vue
             <Root>

**Comment by phegman** [comment]
This has to do with what version of Vue you are importing. Sounds like you are importing the runtime-only version of Vue ([https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only)). However, I just pushed an update that will make this component compatible with the Runtime-only build so if you update your package you should be good to go!
