### ISSUE TITLE
fails on laravel 5.4

### ISSUE THREAD

**Issue by dotslashbin** [phegman/vue-mapbox-gl#2]
Hi, 

I've been trying to implement this on laravel 5.4, and following the instructions carefully. However, I can't seem to pull it off. When I compile using webpack, it does not seem to go through. 

Any workaround for this?

**Comment by phegman** [comment]
Hi Joshua,

Happy to help, but a few more details would be helpful. Are you using Laravel Mix as your build script? What error message do you get when you try and build? Can you provide the code from the JS file you are importing the mapbox component in? 

Thanks,
Pete

**Comment by phegman** [comment]
Closed due to no response
