### ISSUE TITLE
map.setStyle(...)   

### ISSUE THREAD

**Issue by justmark** [phegman/vue-mapbox-gl#26]
Hi,

I've got everything working thus far with your module (fly-to's, searching, pop-ups).  I wanted to give users the option of switching from street view to satellite view.  I have all the controls working for this, but am running into an issue with the setStyle request.

I saved the map object during init so that I can access it from a button click.

I'm using:
```
this.map.setStyle("{style: 'mapbox://styles/mapbox/satellite-v9', center: [-96, 37.8], zoom: 3}")
```

If I set this style as my starting style for the map via :map-options, it works perfectly.  When I try and use the above code though, it appears that the style above is being passed directly to our host, when it obviously can't be resolved.  Here is the console response in the browser:

```
ajax.js:81 GET http://my_host_name/%7Bstyle:%20'mapbox://styles/mapbox/satellite-v9',%20center:%20[-96,%2037.8],%20zoom:%203%7D net::ERR_EMPTY_RESPONSE
exports.getJSON @ ajax.js:81
r.loadURL @ style.js:160
e.setStyle @ map.js:919
styleChange @ Map.vue?54d3:99
boundFn @ vue.esm.js?efeb:191
click @ Map.vue?3249:74
invoker @ vue.esm.js?efeb:2004
fn._withTask.fn._withTask @ vue.esm.js?efeb:1802
08:23:23.779 
```

Any idea what I'm doing wrong?

Thanks

**Comment by phegman** [comment]
Hi Mark,

Without seeing your entire component I am not entirely sure but I was able to get the below example working no problem. Compare your code to the below and see if there is anything different.

```html
<div class="container">
  <mapbox 
    access-token="your access token"
    :map-options="{
      style: 'mapbox://styles/mapbox/light-v9',
      center: [-96, 37.8],
      zoom: 3
    }"
    :geolocate-control="{
      show: true, 
      position: 'top-left'
    }"
    :scale-control="{
      show: true,
      position: 'top-left'
    }"
    :fullscreen-control="{
      show: true,
      position: 'top-left'
    }"
    @map-init="mapInitialized"
    >
  </mapbox>
  <button @click="setStyle" class="set-style">Set Style</button>
</div><!-- /.container -->
```

```js
import Mapbox from 'mapbox-gl-vue';
export default {
  components: { Mapbox },
  data() {
    return {
      map: {}
    }
  },
  methods: {
    mapInitialized(map) {
      this.map = map;
    },
    setStyle() {
      this.map.setStyle('mapbox://styles/mapbox/streets-v9');
    }
  }
}
```

Hope that is helpful!
Pete

**Comment by justmark** [comment]
Hi,

Thanks for looking into this.  Turns out the issue was the JSON being passed to setStyle.  I thought I had read somewhere that it was expecting JSON.  Using just the mapbox reference on its own works perfectly though.

Thanks for the prompt attention, and thanks for this module - its really great.
