### ISSUE TITLE
Repeatedly opening Mapbox.vue with memory leak

### ISSUE THREAD

**Issue by shanligang** [phegman/vue-mapbox-gl#27]
I think Repeatedly opening Mapbox.vue with memory leak。

**Comment by phegman** [comment]
Can you please provide a more detailed explanation of the issue?

**Comment by shanligang** [comment]
Maybe, When you destroy a Map component, you do not destroy an instance of Mapbox-gl.

**Comment by phegman** [comment]
Thanks, PR has been merged!
