### ISSUE TITLE
Problem using Shimming/Universal Import

### ISSUE THREAD

**Issue by jasonmoore30** [phegman/vue-mapbox-gl#29]
Hello,
The instructions say to add the plugin to webpack.config.js, but I am using Vuetify/webpack-advanced and this file doesn't exist. Does this import need to be in the dev.conf.js and prod.conf.js in this case? I've been experimenting, but nothing I have tried has worked. Let me know if this makes sense or if you need more information. Thanks.

**Comment by phegman** [comment]
Hey Jason,

This will vary depending on your Webpack setup. In this case I believe you would want to edit `/build/webpack.base.conf.js` and add:

```js
plugins: [
  new webpack.ProvidePlugin({
    mapboxgl: 'mapbox-gl'
  })
]
```

Hope that is helpful!
Pete
