### ISSUE TITLE
Support for not using style:// and/or mapbox servers

### ISSUE THREAD

**Issue by gorbypark** [phegman/vue-mapbox-gl#32]
I currently use mapbox gl js in a project where we do not use mapbox's servers at all.  We use a private tile and glyph font server.  Using regular mapbox-gl js a sample config might look like this:
```js
var map = new mapboxgl.Map({
  container: 'map',
  style: {
    glyphs: 'https://myglyphs.cloudfront.net/{fontstack}/{range}.pbf',
    version: 8,
    sources: {
      'osm-tiles': {
        type: 'raster',
        tiles: [
          'https://a.tile.mytiles.com/{z}/{x}/{y}.png',
          'https://b.tile.mytiles.com/{z}/{x}/{y}.png'
        ],
        tileSize: 256
      }
    },
    layers: [{
      id: 'osm-tiles',
      type: 'raster',
      source: 'osm-tiles',
      minzoom: 0,
      maxzoom: 22
    }]
  },
  center: [-122.937613, 50.099706], // starting position
  zoom: 12, // starting zoom
  bearing: 150
});
```

We are hopefully transitioning to Vue2 and doing something like this: 
```vue
        <mapbox
          :map-options="{
            style: {
              glyphs: 'https://myglyphs.cloudfront.net/{fontstack}/{range}.pbf',
              version: 8,
              sources: {
                'osm-tiles': {
                  type: 'raster',
                  tiles: [
                    'https://a.tile.mytiles.org/{z}/{x}/{y}.png',
                    'https://b.tile.mytiles.org/{z}/{x}/{y}.png'
                  ],
                  tileSize: 256
                }
              }
            },
            center: [-122.937613, 50.099706],
            zoom: 12,
            bearing: 150
          }"
          :geolocate-control="{
            show: true, 
            position: 'top-right'
          }">
        </mapbox>
```
The results is a blank page and ```[Vue warn]: Missing required prop: "accessToken"``` in the console.  Any idea if this is supported and I'm doing it incorrectly, or if there's any chance of support in the near future?  I tried keeping a valid access token, but the same config as above, and get a blank page with no errors in the console.

**Comment by phegman** [comment]
Hey Mike,

You should be able to just pass the `accessToken` in as an empty string. Since you are hosting your own tiles it sounds like you don't actually need one (although it isn't completely clear in the Mapbox docs). Something like this should work:

```html
<mapbox
	access-token=""
	:map-options="{
		style: {
			glyphs: 'https://myglyphs.cloudfront.net/{fontstack}/{range}.pbf',
			version: 8,
			sources: {
				'osm-tiles': {
					type: 'raster',
					tiles: [
					'https://a.tile.mytiles.org/{z}/{x}/{y}.png',
					'https://b.tile.mytiles.org/{z}/{x}/{y}.png'
					],
					tileSize: 256
				}
			}
		},
		center: [-122.937613, 50.099706],
		zoom: 12,
		bearing: 150
	}"
	:geolocate-control="{
		show: true, 
		position: 'top-left'
	}"
	:scale-control="{
		show: true,
		position: 'top-left'
	}"
	:fullscreen-control="{
		show: true,
		position: 'top-left'
	}"
	@map-init="mapInit"
	@map-load="mapLoaded"
	@map-click="mapClicked"
	@map-mousemove="mapMouseMoved">
</mapbox>
```

The above is rendering all the controls for me but not the tiles so I think it may be an issue with your tiles not loading. I quickly tried the vanilla Mapbox code you provided and got this error in the console: 

GET https://a.tile.mytiles.com/13/1298/2774.png 0 ()
Error
    at XMLHttpRequest.r.onerror (ajax.js:88)
GET https://b.tile.mytiles.com/13/1298/2775.png 0 ()

Hope that is helpful!
Pete

**Comment by gorbypark** [comment]
I forgot to actually add the tile layer in the vue-mapbox code above.  Adding this block, plus passing the empty access-token did the trick!
```js
layers: [{
      id: 'osm-tiles',
      type: 'raster',
      source: 'osm-tiles',
      minzoom: 0,
      maxzoom: 22
    }]
  }
```

Thanks for the incredible support!

**Comment by gorbypark** [comment]
Also, the NYTimes.org was a dummy domain so that's why they wouldn't load.  It's working great with the correct domain!

Thanks again

**Comment by phegman** [comment]
Cheers, good to hear you got it working!
