### ISSUE TITLE
"Missing Mapbox GL JS CSS" when using with Vue-Cli 3

### ISSUE THREAD

**Issue by brianbancroft** [phegman/vue-mapbox-gl#36]
Hi there, and thanks for putting something nice like this together.

I've got an issue where the css isn't loading properly, and I receive the following error:

![image](https://user-images.githubusercontent.com/6225122/39322636-896874d6-4958-11e8-952a-015f5de8835c.png)

The main difference between how I was able to use this library and the docs is that I use the map in a nested component instead of declaring it in the main object in `main.js`. Instead, from within a `MainBody` component, I have the Mapbox component defined from within the export default statement. ~To be clear, the intent is to have the map cover the entire region that is coloured #aaa, but not the part that is white.~ _(Resolved, but the message persists)_

From `MainBody.vue`: 
```vue
<script>
  import Mapbox from 'mapbox-gl-vue'

  export default {
    components: {
      Mapbox
    }
  }
</script>
```

Is there something else that I require to do to make the warning message go away, and to allow the map to take the entire right-hand of the screen (as in the screencap)? 

### Steps to Reproduce
I haven't been able to build this to a fiddle, but I have pushed what I've done in the hopes of clarity. 

- `git clone https://github.com/brianbancroft/analysis-frontend.git --branch feature/demo-vue-issue --single-branch`
- `cd analysis-frontend && yarn && yarn serve`
- Go to `http://localhost:8080`

**Comment by brianbancroft** [comment]
Okay an update: With regards to the map being stuck on the right-hand side. I should have read #11, but the message still persists

![image](https://user-images.githubusercontent.com/6225122/39323244-09206322-495a-11e8-96f2-fe79aa2b9068.png)

**Comment by phegman** [comment]
Hey Brian,

This package does not include the CSS for Mapbox GL JS. I added `<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css' rel='stylesheet' />` to the head of your `index.html` and everything seems to be working well!

Hope that is helpful!
Pete

**Comment by brianbancroft** [comment]
Thanks. This does help. 

At the time when I built the project using the newest  vue-cli, I couldn't find index.html. As Evan kindly points out, it's in the `/public` directory. https://github.com/vuejs/vue-cli/issues/765
