### ISSUE TITLE
How do you access Geolocation (or similar) events?

### ISSUE THREAD

**Issue by toadkicker** [phegman/vue-mapbox-gl#39]
It's not clear how one would access the geolocation control's events through Vue. (https://www.mapbox.com/mapbox-gl-js/api/#geolocatecontrol.event:geolocate) I thought it would be as simple as doing `@map-geolocate`, `@map-trackuserlocationend` but neither bubbled up.

**Comment by toadkicker** [comment]
Also tried:

```
const geo = this.map.addControl(new mapboxgl.GeolocateControl({ show: true, position: 'top-left', positionOptions: { enableHighAccuracy: true }}));
geo.on('geolocate', this.setAddress);
```

**Comment by LKajan** [comment]
Control events are not currently implemented yet. There is a pull request #38 for that though.

**Comment by toadkicker** [comment]
Ok great I will pull that branch and try it out

**Comment by phegman** [comment]
Thanks to @LKajan control events have now been implemented. If you pull down the latest NPM package you should be able to use them. Documentation has also been updated to explain how.

**Comment by toadkicker** [comment]
I upgraded but it doesn't look like it is working properly. Looking at the pull request, it doesn't look like $emit is implemented correctly. According to the [docs](https://vuejs.org/v2/api/#Instance-Methods-Events) the second argument is a callback. In PR #38 it is passing `this.$emit('geolocate-geolocate', geolocate, position)`. Instead we would want to probably pass `this.$emit('geolocate-geolocate', {event: geolocate, position: position})` so that position isn't dropped from the callback.
