### ISSUE TITLE
Using without "mapbox" map

### ISSUE THREAD

**Issue by vinayakkulkarni** [phegman/vue-mapbox-gl#40]
1. https://gis.stackexchange.com/a/260795
2. https://gis.stackexchange.com/questions/188141/mapbox-sdk-is-it-free-if-you-host-your-own-vector-tiles/260795#260795

Just wanted to know whether this wrapper supports using mapbox-gl-js without using the traditional mapbox `access-token`?

**Comment by phegman** [comment]
It does, just pass an empty string to the `access-token` prop. See this issue for more details: https://github.com/phegman/vue-mapbox-gl/issues/32
