### ISSUE TITLE
Multiple map instances

### ISSUE THREAD

**Issue by attx** [phegman/vue-mapbox-gl#41]
I tried to create multiple map instances, but vue-mapbox-gl don't display anything when changing the id attribute of the <mapbox> component. The events (onMapLoaded, ..) get called on the first map too, is it possible somehow to have multiple maps at the same time?

**Comment by phegman** [comment]
Yep this component supports multiple map instances. See this issue for more info: https://github.com/phegman/vue-mapbox-gl/issues/10

Please share your code if you still can't get it working.

Best,
Pete

**Comment by attx** [comment]
Still have the same issue that all events are called on the first map only even with different container id's inside the mapOptions. I'll share an example asap.
