### ISSUE TITLE
Single File Component example please!

### ISSUE THREAD

**Issue by trickidicki** [phegman/vue-mapbox-gl#42]
It would be most useful if your usage documentation included an example of a Single File Component, including how to set options. Thanks.

**Comment by phegman** [comment]
I may add a note about single file components, but essentially there shouldn't be much difference from the examples shown in the docs. The HTML goes in the `<template>` section of the component, the JS goes in the `<script>` section and the CSS goes in the `<style>` section. Feel free to open up a PR with updated docs if you have an idea of how this should be conveyed.
