### ISSUE TITLE
How to add markers to the map

### ISSUE THREAD

**Issue by Waidhoferj** [phegman/vue-mapbox-gl#47]
Hello, I noticed in one of the closed issues, it was possible to add markers which are connected to the Vue data field. I'm working with an app that only needs static markers created when the map loads, but I couldn't find the method to actually create these elements in the documentation for this module or through research online. Could you possibly direct me to a source that covers this process?

**Comment by Waidhoferj** [comment]
Thank you! This really helped!

**Comment by Jones-S** [comment]
Hm I still have problems adding markers.
I try to do this on the `map-load` event, but `mapboxgl` is not defined at that point.
So this `new mapboxgl.Marker(el)` will fail.
I tried to import it at the top:
`import mapboxgl from 'mapbox-gl'` although I thought that adding this in my nuxt.config.js

```
build: {
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ],
}
```
would make it `mapboxgl` available everywhere without the need to import.
But then again I would get this error

>  ReferenceError: self is not defined
Linked to: https://github.com/phegman/vue-mapbox-gl/issues/43

@Waidhoferj  or anyone: How did you end up adding markers?

**Comment by Jones-S** [comment]
I ended up requiring mapbox-gl within my method like proposed here:
https://github.com/mapbox/mapbox-gl-js/issues/4463#issuecomment-386552634

This seems to work, but is maybe not the nicest solution?

```js
methods: {
    addMarkers(map) {
      const mapboxgl = require('mapbox-gl/dist/mapbox-gl')
      const geojson = {
        type: 'FeatureCollection',
        features: [
          {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [-77.032, 38.913]
            },
            properties: {
              title: 'Mapbox',
              description: 'Washington, D.C.'
            }
          },
          {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [-122.414, 37.776]
            },
            properties: {
              title: 'Mapbox',
              description: 'San Francisco, California'
            }
          }
        ]
      }

      geojson.features.forEach((marker) => {
        // create a HTML element for each feature
        const el = document.createElement('div')
        el.className = 'Map__marker'

        // make a marker for each feature and add to the map
        new mapboxgl.Marker(el)
          .setLngLat(marker.geometry.coordinates)
          .addTo(map)
      })
    }
    }
}
```
On the load event
```
    <mapbox
        :access-token="accessToken"
        :map-options="{...}"
        @map-load="addMarkers"
      />
```

**Comment by mornir** [comment]
In my experience I think that it's oftentimes best to just use the Mapbox GL library directly:
```js
mounted() {
  const mapboxgl = require('mapbox-gl')
  const map = new mapboxgl.Map({
      accessToken: 'YOUR_TOKEN',
      container: 'map', // <div id="map"></div>
      style: 'mapbox://styles/mapbox/streets-v9',
      center: [-21.9270884, 64.1436456],
      zoom: 13
  })
  yourMarkersArray.map((marker) => {
    const LngLat = [marker.location.lng, marker.location.lat]
    const popup = marker.description
    new mapboxgl.Marker()
        .setLngLat(LngLat)
        .setPopup(popup)
        .addTo(map)
     })
}
```

**Comment by AEK-BKF** [comment]
@mornir 
Please, I tried your code but it shows me : `Container 'map' not found.`
