### ISSUE TITLE
Updated mapbox support?

### ISSUE THREAD

**Issue by vinayakkulkarni** [phegman/vue-mapbox-gl#49]
Hey,

The mapbox-gl-js team released a new version of mapbox-gl-js - https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.49.0

Can this plugin be updated to support v0.49?

**Comment by phegman** [comment]
I haven't had a chance to test, but is there something specific in v0.49 that does not work with the existing implementation of this package?

**Comment by vinayakkulkarni** [comment]
I manually updated mapbox-gl-js and everything works A-OK!

**Comment by phegman** [comment]
Great, good to hear!
