### ISSUE TITLE
vue-hot-reload-api error

### ISSUE THREAD

**Issue by igal1c0de4n** [phegman/vue-mapbox-gl#52]
Using this package in https://github.com/meteor-vue/vue-meteor-demo
throws this error while app live-reloads:

  ```
"vue-hot-reload-api" in
/Users/igal/work/mapme-story-viewer/node_modules/mapbox-gl-vue/dist/Mapbox.js
(web.browser.legacy)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save vue-hot-reload-api

```
Any idea whats the issue and/or how to fix?

**Comment by phegman** [comment]
Just released v2 of this package, please give that a try and see if this is still an issue
