### ISSUE TITLE
RTL text not supported

### ISSUE THREAD

**Issue by shaniqwa** [phegman/vue-mapbox-gl#53]
Hi, I'm having issues with RTL languages display. Mapbox docs say I should use [mapbox-gl-rtl-text.js](https://github.com/mapbox/mapbox-gl-rtl-text) plugin, which is initialized like this: 

```
mapboxgl.accessToken = 'pk.eyJ1Ijoic2hhbmlxd2EtYSIsImEiOiJjam9wbzF1am8wYm1kM2xwMzRxcTBldHNkIn0.SgEz2_UyEmFJHQ1zGSV0xw';
mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.0/mapbox-gl-rtl-text.js');

var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [44.3763, 33.2788],
    zoom: 11
});
```

Can you please help me initialize this via vue-mapbox-gl? 
thanks!

**Comment by phegman** [comment]
Yes you should be able to do this in the `@map-init` event like so:

```html
<mapbox
  access-token="your access token"
  :map-options="{
      style: 'mapbox://styles/mapbox/light-v9',
      center: [-96, 37.8],
      zoom: 3
  }"
  :geolocate-control="{
      show: true,
      position: 'top-left'
  }"
  :scale-control="{
      show: true,
      position: 'top-left'
  }"
  :fullscreen-control="{
      show: true,
      position: 'top-left'
  }"
  @map-init="mapInitialized">
</mapbox>
```

```js
import Mapbox from 'mapbox-gl-vue';
const app = new Vue({
  el: '#app',
  components: { Mapbox },
  methods: {
    mapInitialized(map) {
      map.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.0/mapbox-gl-rtl-text.js');
    }
  }
});
```

I haven't personally tested but according to the documentation this seems like the logical thing to try. Give that a shot and see if it works!

**Comment by abdelhameedhamdy** [comment]
Hi, I already tested it, but it doesn't work ..

TypeError: map.setRTLTextPlugin is not a function
    at VueComponent.mapInitialized (map.f834d33b7d830e239136.hot-update.js:53)

Could you please give that a look!

**Comment by abdelhameedhamdy** [comment]
I am having an issue with **setRTLTextPlugin**
When navigating between pages and return back to map, I got the following error : 
**Error: setRTLTextPlugin cannot be called multiple times.**

**Comment by mhsattarian** [comment]
Hi @abdelhameedhamdy,
I tried what you said and it didn't worked for me. can you guess what may be wrong?

**Comment by BJTheCod3r** [comment]
This is closed but might help somebody looking into this now;

Do something like this

```
mapInitialized() {
    if (window.mapboxgl.getRTLTextPluginStatus() != "loaded") {
        window.mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.0/mapbox-gl-rtl-text.js')
    }
}

```

**Comment by eladcandroid** [comment]
@abdelhameedhamdy 
Did you succeed in enabling it?
