### ISSUE TITLE
The computed property "accessToken" is already defined as a prop.

### ISSUE THREAD

**Issue by PatrickHeneise** [phegman/vue-mapbox-gl#56]
I'm using `accessToken` as a computed property across my app for authentication. I'm not sure if there is a way to scope `accessToken` to the Mapbox component?

**Comment by nickforddesign** [comment]
I'm not the maintainer but are you adding that as a mixin? You could check to see if the name of the component is 'mapbox' before adding the computed.

**Comment by PatrickHeneise** [comment]
That's an interesting take, I'll give that a try, thanks!

**Comment by phegman** [comment]
Hmm not totally sure why this would be an issue, `accessToken` prop should only be defined internally inside this component and shouldn't have any affect on the rest of the application. If you can post how you are using this component that would be helpful, for now I am closing.

**Comment by nickforddesign** [comment]
@phegmen i think they were using a global mixin to all that property to **all** components

**Comment by phegman** [comment]
Ahh okay that makes sense. I don’t have very much experience with Global Mixins, but it looks like you should be able to customize the merging of props. Here is the documentation: https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies

https://vuejs.org/v2/api/#optionMergeStrategies

It looks like the third param of optionMergeStrategies is the Vue instance so you may be able to detect what component is being merged and exclude it. I have not played around with this at all but this is the route I would explore.

**Comment by PatrickHeneise** [comment]
I'll have a look, thanks!
