### ISSUE TITLE
Container 'Map' Not Found

### ISSUE THREAD

**Issue by jtphan14** [phegman/vue-mapbox-gl#6]
I'm receiving the container 'map' not found error. CSS styles are included in the head.  Am I missing something?

![image](https://cloud.githubusercontent.com/assets/16528956/26609474/27c1c64e-4556-11e7-8d32-452b0f7d378d.png)

```
<script>
  import Mapbox from 'mapbox-gl-vue';
  const mapboxgl = require('mapbox-gl');

  export default {
    props: {
      accessToken: {
        Type: String,
        Required: true
      },
      mapOptions: {
        Type: Object,
        Required: true
      },
    },
    components: {
      'mapbox': Mapbox
    }
  }
</script>

<template>
  <div id="map-welcome" class="map">
    <mapbox
    access-token="pk.*****"
    :map-options="{
    	style: 'mapbox://styles/mapbox/light-v9',
    	center: [-96, 37.8],
    	zoom: 3
    }">
  </mapbox>
  </div>
</template>
```

**Comment by phegman** [comment]
Hi Jacqueline,

I think what you are running into is that the mapboxgl object is not globally registered. I purposely left the main Mapbox GL js file out of this component so individuals could choose how they want to implement it (Mapbox CDN or module bundler). This means that if you want to implement it using a module bundler you will need to require it like this `window.mapboxgl = require('mapbox-gl');`.

Give that a shot and see if it works!

Best,
Pete

**Comment by jtphan14** [comment]
Hi Pete,

Thanks for your help! I still received the same error when requiring it like `window.mapboxgl = require('mapbox-gl');.`. 

I was able to resolve the issue, by adding map to the component container.  

```
  <div id="map" class="map">
    <mapbox
    access-token="pk.eyJ1IjoiamFjcXVlbGluZXBoYW4iLCJhIjoiY2oxZnU4MWlrMDAwMTMzbzBnNzRxZ3N5eCJ9.bXJYNw8YclvLPn7q0jA_pg"
    :map-options="{
    	style: 'mapbox://styles/mapbox/light-v9',
    	center: [-96, 37.8],
    	zoom: 3
    }">
  </mapbox>
```

**Comment by yipcma** [comment]
similar issue with run-time build vue, also:
```
vue.runtime.esm.js?a427:430 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Mapbox>
       <App> at /Users/yipc/repos/Vue-Projects/ftl/src/app.vue
         <Root>
```

**Comment by phegman** [comment]
I can't seem to replicate this issue. Can you provide your code in which you are importing the mapbox-gl-vue package?

**Comment by gzurbach** [comment]
FYI I am also experiencing this issue, but as far as I can tell it is only happening during a hot module reload. And even then, despite the console error the map is able to load. Therefore I do not expect this issue to happen in production. Will report back if I find a way to fix this. @jtphan14 solution does remove the error but causes other issues down the line (when zooming in for instance).
