### ISSUE TITLE
ReferenceError: mapboxgl is not defined     at VueComponent.mapInit

### ISSUE THREAD

**Issue by jparish3** [phegman/vue-mapbox-gl#62]
I have tried the fixes in the closed issue but cannot get results. ReferenceError: mapboxgl is not defined #1

**Comment by rimonmath** [comment]
I am having the same issue

**Comment by bfreed** [comment]
Me too

**Comment by vinayakkulkarni** [comment]
- [x] Solved here in the [docs](https://github.com/phegman/vue-mapbox-gl#importing-mapbox-gl-js-with-webpack)

**Comment by mgiraldo** [comment]
@vinayakkulkarni this shimming is not working for me. if i leave that as is, any call within a component to `mapboxgl` like `new mapboxgl.Popup()` produces the `self is not defined` error when reloading the page. i've been forced to add a `const mapboxgl = require('mapbox-gl/dist/mapbox-gl')` before those calls to have it work. any idea what could be going on? 

this is my nuxt config: 
https://github.com/mgiraldo/livingarchive/blob/44778b321b27777c6f3043cffdbdea8a0bafaeb3/nuxt.config.js 

and a use case in a component (with the `require`):
https://github.com/mgiraldo/livingarchive/blob/44778b321b27777c6f3043cffdbdea8a0bafaeb3/components/ResultsMap.vue#L426-L438

and my plugin file: 
https://github.com/mgiraldo/livingarchive/blob/44778b321b27777c6f3043cffdbdea8a0bafaeb3/plugins/vue-mapboxgl.js

this code works on the client and showing no error on reload. removing the `require` fails.
