### ISSUE TITLE
How to use Marker Events?

### ISSUE THREAD

**Issue by timvan** [phegman/vue-mapbox-gl#63]
Hi,

I am trying to use the Marker events, in particular dragend `marker.on('dragend', doSomething);` 

I get how to use map events... @map-event which doesn't work for markers. I also tried attaching the callback to the new marker when created, using the marker.on method above. End goal is to have a draggable marker that fires an update to an api on dragend, to update the new LongLat. 

Any help is very appreciated,

Thanks

**Comment by timvan** [comment]
fixed it
```  
var marker = new mapboxgl.Marker({
        draggable: true
      })

      marker.on('dragend', e => {
        this.doSomething()
      })
```

**Comment by jupeterson** [comment]
Hi @timvan ,
strange... with your code I get "Uncaught TypeError: marker.on is not a function". Do you instantiate your marker in the @map-load event handler?
