### ISSUE TITLE
v-if not followed while tiles are loading

### ISSUE THREAD

**Issue by TheMapleSyrupCan** [phegman/vue-mapbox-gl#66]
I'm trying to update the visibility of a `MglGeojsonLayer` with a `v-if` and if the map is loading tiles, the value is not listened properly.

If set to `true`, the layer shows regardless
If set to `false`, the layer remains visible and will remain that way until I manually toggle it again.

**Comment by phegman** [comment]
I believe this issue is related to the other Vue Mapbox component here: https://github.com/soal/vue-mapbox
