### ISSUE TITLE
Trying to use latest 2.0.3 with Mapbox.js error

### ISSUE THREAD

**Issue by wyattp11** [phegman/vue-mapbox-gl#69]
Tried to update via npm but when hot server reloads I get:

Module build failed: Error: ENOENT: no such file or directory, open '/node_modules/mapbox-gl-vue/dist/Mapbox.js'

Is this just pointing to the wrong dir? If I manually place the file it breaks the plugin, map doesn't load within vue app.

**Comment by phegman** [comment]
Have you tried deleting your ‘node_modules’ directory and then re-running ‘npm install’ or ‘yarn install’ (depending on which package manager you are using)?

**Comment by wyattp11** [comment]
Awesome, that did it!

Ran npm install --save mapbox-gl-vue@2.0.3 then updated mapbox-gl... new maps working too!
