### ISSUE TITLE
"For larger projects VueMapbox may be a better fit." Don't say that

### ISSUE THREAD

**Issue by transfluxus** [phegman/vue-mapbox-gl#72]
VueMapbox seems to be abandoned.
It depends on an outdated version of mapbox-gl, while your implementation seems more agnostic.
Also I use it with nuxt and a major problem was that the page cannot be entered as the first page of the app, or it would crash in dev mode when reloading it. (https://github.com/soal/vue-mapbox/issues/94)
This never happens to me with this library so far.
keep it up, I will switch to this library in a rather large project.

**Comment by Gaabooo** [comment]
Can we add a MILLION likes to this?

**Comment by phegman** [comment]
@transfluxus thanks, glad you are getting some use out of this package! Good to know, when I added that to the README VueMabox appeared to be in active development. Reference to VueMapbox has been removed from the README!
