### ISSUE TITLE
Certain Maki icons not working

### ISSUE THREAD

**Issue by bencooper222** [phegman/vue-mapbox-gl#9]
I'm attempting to use icons from [here](https://www.mapbox.com/maki-icons/) but some of them (like `parking-garage` are not working). Others like `harbor` work perfectly. Why is that? I'm literally just using the example code in the README (the code right before [this](https://www.mapbox.com/maki-icons/)) but simply substituting out the icon name.

**Comment by phegman** [comment]
Hi Ben,

This is a bit confusing, but not all maki icons come with Mapbox out of the box. Here are the available icons out of the box: https://github.com/mapbox/mapbox-gl-styles/tree/master/sprites/basic-v9/_svg

If there is a maki icon that you would like to use you first have to upload it to Mapbox Studio and then you will be able to reference it. So for example the `parking-garage` icon can be used by downloading maki and then uploading `parking-garage-11.svg` and `parking-garage-15.svg` (found in the icons folder) to mapbox studio.

Hope that is helpful!

Best,
Pete

**Comment by bencooper222** [comment]
Ah thanks - appreciated!
